#!/usr/bin/env python
"""
Entry point for Django's command-line utility for administrative tasks.

This file provides a convenience wrapper for ``django-admin`` that sets the
default settings module for the Django project. It follows the standard
structure generated by ``django-admin startproject`` and makes it easy to
manage your project with commands like ``runserver``, ``migrate`` and
``createsuperuser``.

To use this project, ensure that you have Django and PaddleOCR installed in
your Python environment. See the ``README.md`` for installation
instructions.
"""
import os
import sys


def main() -> None:
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ocr_project.settings')
    try:
        from django.core.management import execute_from_command_line  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and available "
            "on your PYTHONPATH environment variable? Did you forget to "
            "activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()