# Generated by Django 4.2.23 on 2025-08-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        choices=[
                            ("NPT", "NPT"),
                            ("REBUT", "Rebut"),
                            ("DEFAUTS", "Defauts"),
                            ("KOSU", "Kosu"),
                        ],
                        help_text="Document type identifier",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the document type and its structure",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Document Type",
                "verbose_name_plural": "Document Types",
                "ordering": ["type_code"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded PDF file", upload_to="uploads/%Y/%m/%d/"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original name of the uploaded file", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Processing"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Current processing status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed"
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extracted table data in JSON format",
                    ),
                ),
                (
                    "table_count",
                    models.IntegerField(
                        default=0, help_text="Number of tables extracted"
                    ),
                ),
                (
                    "excel_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated Excel file",
                        null=True,
                        upload_to="exports/excel/%Y/%m/%d/",
                    ),
                ),
                (
                    "json_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated JSON file",
                        null=True,
                        upload_to="exports/json/%Y/%m/%d/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of document (NPT, Rebut, Defauts, Kosu)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ocrapp.documenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
